---
abstract: "A development, deployment, and management system for RT\ninstallations."
author:
  - 'Chad Granum E<lt>chad@opensourcery.comE<gt>'
build_requires:
  Test::More: 0.8
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTDevSys
provides:
  RTDevSys:
    file: lib/RTDevSys.pm
    version: 0.05
  RTDevSys::Cmd:
    file: lib/RTDevSys/Cmd.pm
  RTDevSys::Cmd::Command::database:
    file: lib/RTDevSys/Cmd/Command/database.pm
  RTDevSys::Cmd::Command::deploy:
    file: lib/RTDevSys/Cmd/Command/deploy.pm
  RTDevSys::Cmd::Command::init:
    file: lib/RTDevSys/Cmd/Command/init.pm
  RTDevSys::Cmd::Command::plugins:
    file: lib/RTDevSys/Cmd/Command/plugins.pm
  RTDevSys::Cmd::Command::rt:
    file: lib/RTDevSys/Cmd/Command/rt.pm
  RTDevSys::Cmd::Command::run:
    file: lib/RTDevSys/Cmd/Command/run.pm
  RTDevSys::Cmd::Command::server:
    file: lib/RTDevSys/Cmd/Command/server.pm
  RTDevSys::Cmd::Command::system:
    file: lib/RTDevSys/Cmd/Command/system.pm
  RTDevSys::Cmd::Command::test:
    file: lib/RTDevSys/Cmd/Command/test.pm
  RTDevSys::Cmd::Command::versions:
    file: lib/RTDevSys/Cmd/Command/versions.pm
  RTDevSys::Cmd::Command::workflows:
    file: lib/RTDevSys/Cmd/Command/workflows.pm
  RTDevSys::Cmd::Roles::Standard:
    file: lib/RTDevSys/Cmd/Roles/Standard.pm
  RTDevSys::Config:
    file: lib/RTDevSys/Config.pm
  RTDevSys::Config::Build:
    file: lib/RTDevSys/Config/Build.pm
  RTDevSys::Cron:
    file: lib/RTDevSys/Cron.pm
  RTDevSys::DB:
    file: lib/RTDevSys/DB.pm
  RTDevSys::DB::Schema:
    file: lib/RTDevSys/DB/Schema.pm
  RTDevSys::DB::VersionTable:
    file: lib/RTDevSys/DB/VersionTable.pm
  RTDevSys::Manual:
    file: lib/RTDevSys/Manual.pm
  RTDevSys::Plugins:
    file: lib/RTDevSys/Plugins.pm
  RTDevSys::Test:
    file: lib/RTDevSys/Test.pm
  RTDevSys::Util:
    file: lib/RTDevSys/Util.pm
  RTDevSys::Versions:
    file: lib/RTDevSys/Versions.pm
  RTDevSys::Workflows:
    file: lib/RTDevSys/Workflows.pm
requires:
  Cwd: 3.30
  DBD::Pg: v2.13.1
  DBD::SQLite: 1.25
  DBD::mysql: 0
  Data::Dumper: 0
  Exporter: 5.63
  ExtUtils::MakeMaker: 6.50
  Fey: 0.28
  Fey::DBIManager: 0.10
  Fey::Loader: 0.10
  Fey::ORM: 0.24
  File::Path: 2.07
  File::Temp: 0.21
  Module::Build: 0.33
  Module::Install: 0.88
  Moose: 0.79
  MooseX::App::Cmd: 0.04
  MooseX::ClassAttribute: 0.08
  String::Diff: 0.04
  Test::Exception: 0.27
  Test::More: 0.86
  YAML::Syck: 1.07
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.05
